// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQcdMt_9Po9knKC7bZZdmxhybZ7vUHLls',
    appId: '1:352920400108:web:504f8f5f750703d9e1b5c9',
    messagingSenderId: '352920400108',
    projectId: 'mwaks-ai',
    authDomain: 'mwaks-ai.firebaseapp.com',
    storageBucket: 'mwaks-ai.firebasestorage.app',
    measurementId: 'G-G797BE4GN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNnfIlu128luBn6N06wSD40WZ-bAJDSeY',
    appId: '1:352920400108:android:bb0ae986acb0164ae1b5c9',
    messagingSenderId: '352920400108',
    projectId: 'mwaks-ai',
    storageBucket: 'mwaks-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgiuazX1ERjzezSFyCuZouXqLVfSydmbc',
    appId: '1:352920400108:ios:1cc0e303f6394fa4e1b5c9',
    messagingSenderId: '352920400108',
    projectId: 'mwaks-ai',
    storageBucket: 'mwaks-ai.firebasestorage.app',
    iosBundleId: 'com.example.mwaksAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgiuazX1ERjzezSFyCuZouXqLVfSydmbc',
    appId: '1:352920400108:ios:1cc0e303f6394fa4e1b5c9',
    messagingSenderId: '352920400108',
    projectId: 'mwaks-ai',
    storageBucket: 'mwaks-ai.firebasestorage.app',
    iosBundleId: 'com.example.mwaksAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQcdMt_9Po9knKC7bZZdmxhybZ7vUHLls',
    appId: '1:352920400108:web:361698e186df05fae1b5c9',
    messagingSenderId: '352920400108',
    projectId: 'mwaks-ai',
    authDomain: 'mwaks-ai.firebaseapp.com',
    storageBucket: 'mwaks-ai.firebasestorage.app',
    measurementId: 'G-4M17VFHEL0',
  );

}